name: Build Android APK (Phone)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify ZIP exists
        run: |
          test -f SmartAlarm_Capacitor_Kit_v8.zip || (echo "ZIP not found in repo root" && exit 1)
          ls -lh SmartAlarm_Capacitor_Kit_v8.zip

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip project payload
        run: |
          mkdir -p payload
          unzip -q SmartAlarm_Capacitor_Kit_v8.zip -d payload
          echo "Payload contents:"
          ls -la payload
          # the top-level folder inside the zip:
          PAYLOAD_DIR=$(ls payload)
          echo "PAYLOAD_DIR=$PAYLOAD_DIR" >> $GITHUB_ENV

      - name: Init Capacitor app scaffold
        run: |
          # Create a fresh Capacitor app workspace
          mkdir app && cd app
          npm init -y

          # Core Capacitor deps
          npm i @capacitor/core@6 @capacitor/cli@6 @capacitor/android@6

          # Minimal Capacitor config (JSON keeps things simple in CI)
          cat > capacitor.config.json << 'JSON'
          {
            "appId": "com.example.alarm",
            "appName": "Smart Alarm",
            "webDir": "www",
            "bundledWebRuntime": false,
            "server": { "androidScheme": "https" }
          }
          JSON

          # Bring in web assets from the ZIP
          cp -r ../payload/${PAYLOAD_DIR}/www ./www

          # Create Android project
          npx cap add android
          npx cap copy

      - name: Merge native Android alarm code (Kotlin + resources)
        run: |
          cd app
          # Copy raw sounds & layout into the Android module
          mkdir -p android/app/src/main/res/raw
          mkdir -p android/app/src/main/res/layout
          cp -r ../payload/${PAYLOAD_DIR}/android_src/res/raw/* android/app/src/main/res/raw/ 2>/dev/null || true
          cp -r ../payload/${PAYLOAD_DIR}/android_src/res/layout/* android/app/src/main/res/layout/ 2>/dev/null || true

          # Copy Kotlin sources under the same package used by the config
          mkdir -p android/app/src/main/java/com/example/alarm
          cp -r ../payload/${PAYLOAD_DIR}/android_src/com/example/alarm/*.kt android/app/src/main/java/com/example/alarm/

          # Inject manifest permissions + components
          MANIFEST=android/app/src/main/AndroidManifest.xml

          # Add uses-permissions right after <manifest ...>
          perl -0777 -pe 's|(<manifest[^>]*>)|\1\n  <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>\n  <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>\n  <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>\n  <uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT"/>\n  <uses-permission android:name="android.permission.VIBRATE"/>|s' -i $MANIFEST

          # Add Activity/Service/Receivers before </application>
          perl -0777 -pe 's|</application>|  <activity android:name=".AlarmActivity" android:exported="true" android:showWhenLocked="true" android:turnScreenOn="true" android:theme="@android:style/Theme.DeviceDefault.NoActionBar.Fullscreen" />\n  <service android:name=".AlarmService" android:exported="false" android:foregroundServiceType="mediaPlayback" />\n  <receiver android:name=".AlarmReceiver" android:exported="true" />\n  <receiver android:name=".StopReceiver" android:exported="false" />\n</application>|s' -i $MANIFEST

          # Re-copy web to native
          npx cap copy

      - name: Build debug APK
        working-directory: app/android
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartAlarm-debug-apk
          path: app/android/app/build/outputs/apk/debug/app-debug.apk